第二份作業/SecondWeekWork/Models/客戶資料.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondWeekWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶資料
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }
    
        public int Id { get; set; }
        public string 客戶名稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 電話 { get; set; }
        public string 傳真 { get; set; }
        public string 地址 { get; set; }
        public string Email { get; set; }
        public bool IsDeleted { get; set; }
        public string 客戶分類 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }
    }
}

第二份作業/SecondWeekWork/Controllers/客戶資料Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SecondWeekWork.Models;
using PagedList;

namespace SecondWeekWork.Controllers
{
    public class 客戶資料Controller : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        客戶資料Repository repo = RepositoryHelper.Get客戶資料Repository();

        // GET: 客戶資料
        public ActionResult Index(string keyword, Object[] level, string sortBy, int pageNo = 1)
        {
            var data = repo.GetByFilter(keyword, level);
            //var data = repo.All();
            //if (string.IsNullOrEmpty(keyword) == false)
            //{
            //    data = data.Where(s => s.客戶名稱.Contains(keyword));
            //}
            //if (level != null && level.Count() > 0)
            //{
            //    string str = level[0].ToString();
            //    data = data.Where(s => s.客戶分類.Contains(str));
            //}
            ViewBag.keyword = keyword;
            ViewBag.level = level;
            ViewBag.sortBy = sortBy;
            ViewBag.pageNo = pageNo;

            if (string.IsNullOrEmpty(sortBy) == false)
            {
                switch (sortBy)
                {
                    case "+客戶分類":
                        data = data.OrderByDescending(s => s.客戶分類);
                    break;
                    case "-客戶分類":
                        data = data.OrderBy(s => s.客戶分類);
                        break;
                    case "+客戶名稱":
                        data = data.OrderByDescending(s => s.客戶名稱);
                        break;
                    case "-客戶名稱":
                        data = data.OrderBy(s => s.客戶名稱);
                        break;
                    case "+統一編號":
                        data = data.OrderByDescending(s => s.統一編號);
                        break;
                    case "-統一編號":
                        data = data.OrderBy(s => s.統一編號);
                        break;
                    case "+電話":
                        data = data.OrderByDescending(s => s.電話);
                        break;
                    case "-電話":
                        data = data.OrderBy(s => s.電話);
                        break;
                    case "+傳真":
                        data = data.OrderByDescending(s => s.傳真);
                        break;
                    case "-傳真":
                        data = data.OrderBy(s => s.傳真);
                        break;
                    case "+地址":
                        data = data.OrderByDescending(s => s.地址);
                        break;
                    case "-地址":
                        data = data.OrderBy(s => s.地址);
                        break;
                    case "+Email":
                        data = data.OrderByDescending(s => s.Email);
                        break;
                    case "-Email":
                        data = data.OrderBy(s => s.Email);
                        break;
                    default:
                        data = data.OrderByDescending(s => s.客戶名稱);
                        break;
                }
            }                
            else
                data = data.OrderByDescending(s => s.客戶名稱);

            return View(data.ToPagedList(pageNo,10));
        }

        // GET: 客戶資料/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = repo.Find(id);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // GET: 客戶資料/Create
        public ActionResult Create()
        {
            //List<SelectListItem> selectItemList = new List<SelectListItem>();
            //selectItemList.Add(new SelectListItem() { Text = "高", Value = "高" });
            //selectItemList.Add(new SelectListItem() { Text = "中", Value = "中", Selected = true, });
            //selectItemList.Add(new SelectListItem() { Text = "低", Value = "低" });

            //ViewData["客戶分類List"] = selectItemList;


            return View();
        }

        // POST: 客戶資料/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(客戶資料 客戶資料)
        {

            if (ModelState.IsValid)
            {
                repo.Add(客戶資料);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            return View(客戶資料);
        }

        // GET: 客戶資料/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = repo.Find(id);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(客戶資料 客戶資料)
        {

            if (ModelState.IsValid)
            {
                repo.Modify(客戶資料);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }
            return View(客戶資料);
        }

        // GET: 客戶資料/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶資料 客戶資料 = repo.Find(id);
            if (客戶資料 == null)
            {
                return HttpNotFound();
            }
            return View(客戶資料);
        }

        // POST: 客戶資料/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            客戶資料 客戶資料 = repo.Find(id);
            repo.Delete(客戶資料);
            repo.UnitOfWork.Commit();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

第二份作業/SecondWeekWork/Views/客戶資料/Create.cshtml
@model SecondWeekWork.Models.客戶資料

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.客戶分類, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.客戶分類, new SelectList(
                  new List<Object>{
                       new { value = 0 , text = "高"  },
                       new { value = 1 , text = "中" },
                       new { value = 2 , text = "低"}
                    },
                  "value",
                  "text",
                   2))

                @*@Html.EditorFor(model => model.客戶分類, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.客戶分類, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

第二份作業/SecondWeekWork/Views/客戶資料/Delete.cshtml
@model SecondWeekWork.Models.客戶資料

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

第二份作業/SecondWeekWork/Views/客戶資料/Details.cshtml
@model SecondWeekWork.Models.客戶資料

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶名稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.統一編號)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.統一編號)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.傳真)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.傳真)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.地址)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.地址)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

第二份作業/SecondWeekWork/Views/客戶資料/Edit.cshtml
@model SecondWeekWork.Models.客戶資料

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶名稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.客戶名稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.客戶名稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.客戶分類, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
@*                @Html.DropDownListFor(model => model.客戶分類, Model.客戶分類SelectList)*@
                @Html.DropDownListFor(model => model.客戶分類, new SelectList(
                  new List<Object>{
                       new { value = 0 , text = "高"  },
                       new { value = 1 , text = "中" },
                       new { value = 2 , text = "低"}
                    },
                  "value",
                  "text",
                   2))


                @Html.ValidationMessageFor(model => model.客戶分類, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.統一編號, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.統一編號, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.統一編號, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.傳真, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.傳真, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.傳真, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.地址, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.地址, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.地址, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

第二份作業/SecondWeekWork/Views/客戶資料/Index.cshtml
@model IEnumerable<SecondWeekWork.Models.客戶資料>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    <form>
        客戶名稱:
        @Html.TextBox("keyword")
    </form>

    <form>
        客戶分類
        @Html.DropDownList("level", new SelectList(
                  new List<Object>{
                       new { value = 3 , text = "請選擇"},
                       new { value = 0 , text = "高"  },
                       new { value = 1 , text = "中" },
                       new { value = 2 , text = "低"},
                    },
                  "value",
                  "text",
                   3))


        <input type="submit" , name="搜尋" />
    </form>
</p>
<table class="table">
    <tr>
        <th>
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "+客戶分類", keyword = ViewBag.keyword })">↑</a>
            @Html.DisplayNameFor(model => model.客戶分類)
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "-客戶分類", keyword = ViewBag.keyword })">↓</a>
        </th>
        <th>
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "+客戶名稱", keyword = ViewBag.keyword })">↑</a>
            @Html.DisplayNameFor(model => model.客戶名稱)
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "-客戶名稱", keyword = ViewBag.keyword })">↓</a>
        </th>
        <th>
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "+統一編號", keyword = ViewBag.keyword })">↑</a>
            @Html.DisplayNameFor(model => model.統一編號)
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "-統一編號", keyword = ViewBag.keyword })">↓</a>
        </th>
        <th>
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "+電話", keyword = ViewBag.keyword })">↑</a>
            @Html.DisplayNameFor(model => model.電話)
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "-電話", keyword = ViewBag.keyword })">↓</a>
        </th>
        <th>
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "+傳真", keyword = ViewBag.keyword })">↑</a>
            @Html.DisplayNameFor(model => model.傳真)
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "-傳真", keyword = ViewBag.keyword })">↓</a>
        </th>
        <th>
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "+地址", keyword = ViewBag.keyword })">↑</a>
            @Html.DisplayNameFor(model => model.地址)
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "-地址", keyword = ViewBag.keyword })">↓</a>
        </th>
        <th>
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "+Email", keyword = ViewBag.keyword })">↑</a>
            @Html.DisplayNameFor(model => model.Email)
            <a href="@Url.Action("Index", "客戶資料", new { sortBy = "-Email", keyword = ViewBag.keyword })">↓</a>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.客戶分類)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.客戶名稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.統一編號)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.電話)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.傳真)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.地址)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

@using PagedList
@using PagedList.Mvc

@Html.PagedListPager(Model as IPagedList, (p) => Url.Action("Index", new { ViewBag.sortBy, ViewBag.keyword, pageNo = p }))